lib/metrics-api.rb
lib/models/metrics.rb

Add some indexes to mongodb

---

Guardfile
features/content-types.feature
lib/metrics-api.rb
lib/views/frames.erb
questions.md

Render iframes

---

lib/metrics-api.rb
lib/public/css/styles.css
lib/public/javascripts/metrics.js
lib/views/layouts/rich.erb
lib/views/metric.erb
lib/views/target.erb
spec/javascripts/metrics_spec.js

This is a bit WIP but it should merge safely

With target

---

config/metrics.yml
lib/metrics-api.rb
lib/public/css/styles.css
lib/public/javascripts/tasklist.js
lib/views/tasklist.erb
spec/javascripts/helpers/jasmine-jquery.js
spec/javascripts/support/jasmine.yml
spec/javascripts/tasklist_spec.js

Just a simple list with progress bars for now. Nothing too fancy, but it works

Show task list

---

config.ru
config/metrics.yml
lib/metrics-api.rb
lib/public/javascripts/metrics.js
lib/views/pie.erb
spec/javascripts/metrics_spec.js

Pie chart view

---

lib/public/css/styles.css
lib/public/javascripts/metrics.js
spec/javascripts/metrics_spec.js

I found a bug in the progress bar, and then I couldn't stop fiddling. Here's how the progress bars look now:

Tweak progress

---

features/query-strings.feature
features/support/env.rb
features/support/hooks.rb
lib/metrics-api.rb
lib/metrics-api/date-wrangler.rb
lib/metrics-api/helpers.rb
lib/views/number.erb
spec/date-wrangler_spec.rb
spec/helpers/helpers_spec.rb
spec/helpers/string_spec.rb

Refactorings

---

lib/public/javascripts/number.js
lib/views/number.erb
spec/javascripts/number_spec.js
spec/javascripts/support/jasmine.yml

Moved the numbers logic to a seperate js file and added tests. We should probably do this with all the views TBH

Refactor numbers view with tests

---

lib/metrics-api.rb

Couple of bugs that manifested themselves when setting up the demo instance

Various bugs

---

Rakefile

We can then set this to run daily on Heroku scheduler to get rid of any cruft that may get added

Add script to set demo up

---

.gitignore
lib/public/javascripts/target.js
spec/javascripts/fixtures/target.html
spec/javascripts/support/jasmine.yml
spec/javascripts/target_spec.js

Now we don't get an `undefined` when the YTD flag is not set. Also some Jasmine tests and a minor refactor

Make YTD flag optional

---

lib/metrics-api.rb
lib/metrics-api/helpers.rb
spec/helpers/helpers_spec.rb

For #65 
Got myself tied in knots a bit with this, but I think the best solution is to work this out, rather than display a number for everything

Work out if a metric needs to display a range or single by default

---

lib/public/javascripts/metrics.js
lib/public/javascripts/number.js
lib/public/javascripts/target.js
spec/javascripts/metrics_spec.js

Loooooooong numbers

---

Rakefile

Make sure targets are lower than actuals

---

lib/metrics-api.rb
lib/public/javascripts/metrics.js
lib/views/includes/configuration-form.erb
spec/javascripts/metrics_spec.js

This now lets us do all the option changing on the fly, rather than on the server, which is much more responsive, and also removes any possibility of error with dates etc.

Improve metric options

---

lib/metrics-api/helpers.rb
lib/views/includes/header.erb
spec/helpers/helpers_spec.rb

This should fix titles not showing in the demo instance

Title tweaks

---

lib/public/css/target.css
lib/public/javascripts/target.js
lib/views/pie.erb
spec/javascripts/target_spec.js

It looked like this:
Now looks like this:

Show target as less than 100% if actual is over target

---

lib/public/javascripts/chart.js

Plotly is clever about all this. Resolves #123

Let dates auto-format

---

lib/metrics-api/helpers.rb
lib/public/css/target.css
lib/public/javascripts/chart.js
lib/public/javascripts/number.js
lib/views/chart.erb
lib/views/number.erb
lib/views/pie.erb
lib/views/target.erb
spec/javascripts/number_spec.js

And also make the date format user configurable

Add last updated to all views

---

_includes/documentation.md

Creating new metrics, that it's currently impossible to delete metrics and that metric description can be set via Bothan front-end on Heroku

Suggestions on metrics

---

lib/public/javascripts/chart.js
lib/public/javascripts/number.js
lib/views/chart.erb
lib/views/includes/rich-header.erb
lib/views/number.erb
lib/views/pie.erb
lib/views/target.erb
spec/javascripts/number_spec.js
spec/javascripts/support/jasmine.yml

Display when things were updated in words

---

visualisations.md

Chrome & FF block the iframes, due to mixed content. Hopefully this
fixes that.

https everywhere

---

lib/metrics-api/helpers.rb
lib/public/javascripts/dashboard.js
spec/javascripts/dashboard_spec.js

Couple of fixes for dashboards that have cropped up while building the Digicat ones

Dashboard fixes

---

features/incrementing-metrics.feature
features/step_definitions/post_steps.rb
lib/metrics-api.rb
lib/metrics-api/helpers.rb

Increment metrics

---

docs/_layouts/default.html
docs/adding-data.md
docs/building-a-dashboard.md
docs/setting-up.md
docs/stylesheets/embed-responsively.css

including @pezholio wonderful screencast tutorials to bothan in the tutorial docs for Bothan
Add additions to docs folder so no new tests added

Include screencast documentation

---

README.md

remove duplication, include links to dev libraries

amendments to readme

---

.github/CONTRIBUTING.md

ensuring consistency here before parcelling out to other repos https://github.com/theodi/toolbox/wiki/Code-Review-Process

update contributing in line with toolbox wiki

---

app.json

Fix Heroku deployment

---

README.md

this is helpful information for a new contributor to have spelled out

update with info on how to have demo metrics
